const meeting = {
    GET_METER_DATA_INIT: "GET_METER_DATA_INIT",
    GET_METER_DATA_SUCCESS: "GET_METER_DATA_SUCCESS",
    GET_METER_DATA_FAILED: "GET_METER_DATA_FAILED",

    GET_METER_DATA_SPINNER_ON: "GET_METER_DATA_SPINNER_ON",
    GET_METER_DATA_SPINNER_OFF: "GET_METER_DATA_SPINNER_OFF",

    GET_MEETING_DATA_INIT: "GET_MEETING_DATA_INIT",
    GET_MEETING_DATA_SUCCESS: "GET_MEETING_DATA_SUCCESS",
    GET_MEETING_DATA_FAILED: "GET_MEETING_DATA_FAILED",

    GET_MEETING_DATA_SPINNER_ON: "GET_MEETING_DATA_SPINNER_ON",
    GET_MEETING_DATA_SPINNER_OFF: "GET_MEETING_DATA_SPINNER_OFF",
}

export { meeting }